recipe:
  security:
    apiMatcher: "/api/**"
    cors:
      allowedOrigins: "*"
      allowedHeaders: "*"
      exposedHeaders: Location, Content-Disposition
      allowedMethods: GET,POST,PUT,DELETE,OPTIONS
      allowCredentials: true
      maxAge: 3600

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  profiles:
    active: dev
  main.allow-bean-definition-overriding: true
  servlet.multipart.max-file-size: 20MB
  jackson:
    serialization.FAIL_ON_EMPTY_BEANS: false
    mapper.ACCEPT_CASE_INSENSITIVE_ENUMS: true
